/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedUsuariosRouteImport } from './routes/_authenticated/usuarios'
import { Route as AuthenticatedSugestoesCompraRouteImport } from './routes/_authenticated/sugestoes-compra'
import { Route as AuthenticatedRelatoriosRouteImport } from './routes/_authenticated/relatorios'
import { Route as AuthenticatedMovimentacoesRouteImport } from './routes/_authenticated/movimentacoes'
import { Route as AuthenticatedManutencaoRouteImport } from './routes/_authenticated/manutencao'
import { Route as AuthenticatedLicencasRouteImport } from './routes/_authenticated/licencas'
import { Route as AuthenticatedFornecedoresRouteImport } from './routes/_authenticated/fornecedores'
import { Route as AuthenticatedEtiquetasRouteImport } from './routes/_authenticated/etiquetas'
import { Route as AuthenticatedEmpresasRouteImport } from './routes/_authenticated/empresas'
import { Route as AuthenticatedDescobertaRouteImport } from './routes/_authenticated/descoberta'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedContratosRouteImport } from './routes/_authenticated/contratos'
import { Route as AuthenticatedConsumiveisRouteImport } from './routes/_authenticated/consumiveis'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedCategoriasRouteImport } from './routes/_authenticated/categorias'
import { Route as AuthenticatedAuditoriaRouteImport } from './routes/_authenticated/auditoria'
import { Route as AuthenticatedAlertasRouteImport } from './routes/_authenticated/alertas'
import { Route as AuthenticatedA3AgentRouteImport } from './routes/_authenticated/a3-agent'
import { Route as AuthenticatedImpressorasIndexRouteImport } from './routes/_authenticated/impressoras.index'
import { Route as AuthenticatedAtivosIndexRouteImport } from './routes/_authenticated/ativos.index'
import { Route as AuthenticatedImpressorasNovoRouteImport } from './routes/_authenticated/impressoras.novo'
import { Route as AuthenticatedImpressorasIdRouteImport } from './routes/_authenticated/impressoras.$id'
import { Route as AuthenticatedAtivosNovoRouteImport } from './routes/_authenticated/ativos.novo'
import { Route as AuthenticatedAtivosIdRouteImport } from './routes/_authenticated/ativos.$id'
import { Route as ApiPublicPrintersIngestRouteImport } from './routes/api/public/printers/ingest'
import { Route as ApiPublicAgentHeartbeatRouteImport } from './routes/api/public/agent/heartbeat'
import { Route as ApiPublicAgentDiscoveryRouteImport } from './routes/api/public/agent/discovery'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUsuariosRoute = AuthenticatedUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSugestoesCompraRoute =
  AuthenticatedSugestoesCompraRouteImport.update({
    id: '/sugestoes-compra',
    path: '/sugestoes-compra',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRelatoriosRoute = AuthenticatedRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMovimentacoesRoute =
  AuthenticatedMovimentacoesRouteImport.update({
    id: '/movimentacoes',
    path: '/movimentacoes',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedManutencaoRoute = AuthenticatedManutencaoRouteImport.update({
  id: '/manutencao',
  path: '/manutencao',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLicencasRoute = AuthenticatedLicencasRouteImport.update({
  id: '/licencas',
  path: '/licencas',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFornecedoresRoute =
  AuthenticatedFornecedoresRouteImport.update({
    id: '/fornecedores',
    path: '/fornecedores',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedEtiquetasRoute = AuthenticatedEtiquetasRouteImport.update({
  id: '/etiquetas',
  path: '/etiquetas',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEmpresasRoute = AuthenticatedEmpresasRouteImport.update({
  id: '/empresas',
  path: '/empresas',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDescobertaRoute = AuthenticatedDescobertaRouteImport.update({
  id: '/descoberta',
  path: '/descoberta',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedContratosRoute = AuthenticatedContratosRouteImport.update({
  id: '/contratos',
  path: '/contratos',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedConsumiveisRoute =
  AuthenticatedConsumiveisRouteImport.update({
    id: '/consumiveis',
    path: '/consumiveis',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCategoriasRoute = AuthenticatedCategoriasRouteImport.update({
  id: '/categorias',
  path: '/categorias',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAuditoriaRoute = AuthenticatedAuditoriaRouteImport.update({
  id: '/auditoria',
  path: '/auditoria',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAlertasRoute = AuthenticatedAlertasRouteImport.update({
  id: '/alertas',
  path: '/alertas',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedA3AgentRoute = AuthenticatedA3AgentRouteImport.update({
  id: '/a3-agent',
  path: '/a3-agent',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedImpressorasIndexRoute =
  AuthenticatedImpressorasIndexRouteImport.update({
    id: '/impressoras/',
    path: '/impressoras/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAtivosIndexRoute =
  AuthenticatedAtivosIndexRouteImport.update({
    id: '/ativos/',
    path: '/ativos/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedImpressorasNovoRoute =
  AuthenticatedImpressorasNovoRouteImport.update({
    id: '/impressoras/novo',
    path: '/impressoras/novo',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedImpressorasIdRoute =
  AuthenticatedImpressorasIdRouteImport.update({
    id: '/impressoras/$id',
    path: '/impressoras/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAtivosNovoRoute = AuthenticatedAtivosNovoRouteImport.update({
  id: '/ativos/novo',
  path: '/ativos/novo',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAtivosIdRoute = AuthenticatedAtivosIdRouteImport.update({
  id: '/ativos/$id',
  path: '/ativos/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiPublicPrintersIngestRoute = ApiPublicPrintersIngestRouteImport.update({
  id: '/api/public/printers/ingest',
  path: '/api/public/printers/ingest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAgentHeartbeatRoute = ApiPublicAgentHeartbeatRouteImport.update({
  id: '/api/public/agent/heartbeat',
  path: '/api/public/agent/heartbeat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAgentDiscoveryRoute = ApiPublicAgentDiscoveryRouteImport.update({
  id: '/api/public/agent/discovery',
  path: '/api/public/agent/discovery',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/a3-agent': typeof AuthenticatedA3AgentRoute
  '/alertas': typeof AuthenticatedAlertasRoute
  '/auditoria': typeof AuthenticatedAuditoriaRoute
  '/categorias': typeof AuthenticatedCategoriasRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/consumiveis': typeof AuthenticatedConsumiveisRoute
  '/contratos': typeof AuthenticatedContratosRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/descoberta': typeof AuthenticatedDescobertaRoute
  '/empresas': typeof AuthenticatedEmpresasRoute
  '/etiquetas': typeof AuthenticatedEtiquetasRoute
  '/fornecedores': typeof AuthenticatedFornecedoresRoute
  '/licencas': typeof AuthenticatedLicencasRoute
  '/manutencao': typeof AuthenticatedManutencaoRoute
  '/movimentacoes': typeof AuthenticatedMovimentacoesRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/sugestoes-compra': typeof AuthenticatedSugestoesCompraRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
  '/ativos/$id': typeof AuthenticatedAtivosIdRoute
  '/ativos/novo': typeof AuthenticatedAtivosNovoRoute
  '/impressoras/$id': typeof AuthenticatedImpressorasIdRoute
  '/impressoras/novo': typeof AuthenticatedImpressorasNovoRoute
  '/ativos/': typeof AuthenticatedAtivosIndexRoute
  '/impressoras/': typeof AuthenticatedImpressorasIndexRoute
  '/api/public/agent/discovery': typeof ApiPublicAgentDiscoveryRoute
  '/api/public/agent/heartbeat': typeof ApiPublicAgentHeartbeatRoute
  '/api/public/printers/ingest': typeof ApiPublicPrintersIngestRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/a3-agent': typeof AuthenticatedA3AgentRoute
  '/alertas': typeof AuthenticatedAlertasRoute
  '/auditoria': typeof AuthenticatedAuditoriaRoute
  '/categorias': typeof AuthenticatedCategoriasRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/consumiveis': typeof AuthenticatedConsumiveisRoute
  '/contratos': typeof AuthenticatedContratosRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/descoberta': typeof AuthenticatedDescobertaRoute
  '/empresas': typeof AuthenticatedEmpresasRoute
  '/etiquetas': typeof AuthenticatedEtiquetasRoute
  '/fornecedores': typeof AuthenticatedFornecedoresRoute
  '/licencas': typeof AuthenticatedLicencasRoute
  '/manutencao': typeof AuthenticatedManutencaoRoute
  '/movimentacoes': typeof AuthenticatedMovimentacoesRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/sugestoes-compra': typeof AuthenticatedSugestoesCompraRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
  '/ativos/$id': typeof AuthenticatedAtivosIdRoute
  '/ativos/novo': typeof AuthenticatedAtivosNovoRoute
  '/impressoras/$id': typeof AuthenticatedImpressorasIdRoute
  '/impressoras/novo': typeof AuthenticatedImpressorasNovoRoute
  '/ativos': typeof AuthenticatedAtivosIndexRoute
  '/impressoras': typeof AuthenticatedImpressorasIndexRoute
  '/api/public/agent/discovery': typeof ApiPublicAgentDiscoveryRoute
  '/api/public/agent/heartbeat': typeof ApiPublicAgentHeartbeatRoute
  '/api/public/printers/ingest': typeof ApiPublicPrintersIngestRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/a3-agent': typeof AuthenticatedA3AgentRoute
  '/_authenticated/alertas': typeof AuthenticatedAlertasRoute
  '/_authenticated/auditoria': typeof AuthenticatedAuditoriaRoute
  '/_authenticated/categorias': typeof AuthenticatedCategoriasRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/consumiveis': typeof AuthenticatedConsumiveisRoute
  '/_authenticated/contratos': typeof AuthenticatedContratosRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/descoberta': typeof AuthenticatedDescobertaRoute
  '/_authenticated/empresas': typeof AuthenticatedEmpresasRoute
  '/_authenticated/etiquetas': typeof AuthenticatedEtiquetasRoute
  '/_authenticated/fornecedores': typeof AuthenticatedFornecedoresRoute
  '/_authenticated/licencas': typeof AuthenticatedLicencasRoute
  '/_authenticated/manutencao': typeof AuthenticatedManutencaoRoute
  '/_authenticated/movimentacoes': typeof AuthenticatedMovimentacoesRoute
  '/_authenticated/relatorios': typeof AuthenticatedRelatoriosRoute
  '/_authenticated/sugestoes-compra': typeof AuthenticatedSugestoesCompraRoute
  '/_authenticated/usuarios': typeof AuthenticatedUsuariosRoute
  '/_authenticated/ativos/$id': typeof AuthenticatedAtivosIdRoute
  '/_authenticated/ativos/novo': typeof AuthenticatedAtivosNovoRoute
  '/_authenticated/impressoras/$id': typeof AuthenticatedImpressorasIdRoute
  '/_authenticated/impressoras/novo': typeof AuthenticatedImpressorasNovoRoute
  '/_authenticated/ativos/': typeof AuthenticatedAtivosIndexRoute
  '/_authenticated/impressoras/': typeof AuthenticatedImpressorasIndexRoute
  '/api/public/agent/discovery': typeof ApiPublicAgentDiscoveryRoute
  '/api/public/agent/heartbeat': typeof ApiPublicAgentHeartbeatRoute
  '/api/public/printers/ingest': typeof ApiPublicPrintersIngestRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/a3-agent'
    | '/alertas'
    | '/auditoria'
    | '/categorias'
    | '/configuracoes'
    | '/consumiveis'
    | '/contratos'
    | '/dashboard'
    | '/descoberta'
    | '/empresas'
    | '/etiquetas'
    | '/fornecedores'
    | '/licencas'
    | '/manutencao'
    | '/movimentacoes'
    | '/relatorios'
    | '/sugestoes-compra'
    | '/usuarios'
    | '/ativos/$id'
    | '/ativos/novo'
    | '/impressoras/$id'
    | '/impressoras/novo'
    | '/ativos/'
    | '/impressoras/'
    | '/api/public/agent/discovery'
    | '/api/public/agent/heartbeat'
    | '/api/public/printers/ingest'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/a3-agent'
    | '/alertas'
    | '/auditoria'
    | '/categorias'
    | '/configuracoes'
    | '/consumiveis'
    | '/contratos'
    | '/dashboard'
    | '/descoberta'
    | '/empresas'
    | '/etiquetas'
    | '/fornecedores'
    | '/licencas'
    | '/manutencao'
    | '/movimentacoes'
    | '/relatorios'
    | '/sugestoes-compra'
    | '/usuarios'
    | '/ativos/$id'
    | '/ativos/novo'
    | '/impressoras/$id'
    | '/impressoras/novo'
    | '/ativos'
    | '/impressoras'
    | '/api/public/agent/discovery'
    | '/api/public/agent/heartbeat'
    | '/api/public/printers/ingest'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/a3-agent'
    | '/_authenticated/alertas'
    | '/_authenticated/auditoria'
    | '/_authenticated/categorias'
    | '/_authenticated/configuracoes'
    | '/_authenticated/consumiveis'
    | '/_authenticated/contratos'
    | '/_authenticated/dashboard'
    | '/_authenticated/descoberta'
    | '/_authenticated/empresas'
    | '/_authenticated/etiquetas'
    | '/_authenticated/fornecedores'
    | '/_authenticated/licencas'
    | '/_authenticated/manutencao'
    | '/_authenticated/movimentacoes'
    | '/_authenticated/relatorios'
    | '/_authenticated/sugestoes-compra'
    | '/_authenticated/usuarios'
    | '/_authenticated/ativos/$id'
    | '/_authenticated/ativos/novo'
    | '/_authenticated/impressoras/$id'
    | '/_authenticated/impressoras/novo'
    | '/_authenticated/ativos/'
    | '/_authenticated/impressoras/'
    | '/api/public/agent/discovery'
    | '/api/public/agent/heartbeat'
    | '/api/public/printers/ingest'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiPublicAgentDiscoveryRoute: typeof ApiPublicAgentDiscoveryRoute
  ApiPublicAgentHeartbeatRoute: typeof ApiPublicAgentHeartbeatRoute
  ApiPublicPrintersIngestRoute: typeof ApiPublicPrintersIngestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/usuarios': {
      id: '/_authenticated/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof AuthenticatedUsuariosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/sugestoes-compra': {
      id: '/_authenticated/sugestoes-compra'
      path: '/sugestoes-compra'
      fullPath: '/sugestoes-compra'
      preLoaderRoute: typeof AuthenticatedSugestoesCompraRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/relatorios': {
      id: '/_authenticated/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof AuthenticatedRelatoriosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/movimentacoes': {
      id: '/_authenticated/movimentacoes'
      path: '/movimentacoes'
      fullPath: '/movimentacoes'
      preLoaderRoute: typeof AuthenticatedMovimentacoesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/manutencao': {
      id: '/_authenticated/manutencao'
      path: '/manutencao'
      fullPath: '/manutencao'
      preLoaderRoute: typeof AuthenticatedManutencaoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/licencas': {
      id: '/_authenticated/licencas'
      path: '/licencas'
      fullPath: '/licencas'
      preLoaderRoute: typeof AuthenticatedLicencasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/fornecedores': {
      id: '/_authenticated/fornecedores'
      path: '/fornecedores'
      fullPath: '/fornecedores'
      preLoaderRoute: typeof AuthenticatedFornecedoresRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/etiquetas': {
      id: '/_authenticated/etiquetas'
      path: '/etiquetas'
      fullPath: '/etiquetas'
      preLoaderRoute: typeof AuthenticatedEtiquetasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/empresas': {
      id: '/_authenticated/empresas'
      path: '/empresas'
      fullPath: '/empresas'
      preLoaderRoute: typeof AuthenticatedEmpresasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/descoberta': {
      id: '/_authenticated/descoberta'
      path: '/descoberta'
      fullPath: '/descoberta'
      preLoaderRoute: typeof AuthenticatedDescobertaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/contratos': {
      id: '/_authenticated/contratos'
      path: '/contratos'
      fullPath: '/contratos'
      preLoaderRoute: typeof AuthenticatedContratosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/consumiveis': {
      id: '/_authenticated/consumiveis'
      path: '/consumiveis'
      fullPath: '/consumiveis'
      preLoaderRoute: typeof AuthenticatedConsumiveisRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/categorias': {
      id: '/_authenticated/categorias'
      path: '/categorias'
      fullPath: '/categorias'
      preLoaderRoute: typeof AuthenticatedCategoriasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/auditoria': {
      id: '/_authenticated/auditoria'
      path: '/auditoria'
      fullPath: '/auditoria'
      preLoaderRoute: typeof AuthenticatedAuditoriaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/alertas': {
      id: '/_authenticated/alertas'
      path: '/alertas'
      fullPath: '/alertas'
      preLoaderRoute: typeof AuthenticatedAlertasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/a3-agent': {
      id: '/_authenticated/a3-agent'
      path: '/a3-agent'
      fullPath: '/a3-agent'
      preLoaderRoute: typeof AuthenticatedA3AgentRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/impressoras/': {
      id: '/_authenticated/impressoras/'
      path: '/impressoras'
      fullPath: '/impressoras/'
      preLoaderRoute: typeof AuthenticatedImpressorasIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ativos/': {
      id: '/_authenticated/ativos/'
      path: '/ativos'
      fullPath: '/ativos/'
      preLoaderRoute: typeof AuthenticatedAtivosIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/impressoras/novo': {
      id: '/_authenticated/impressoras/novo'
      path: '/impressoras/novo'
      fullPath: '/impressoras/novo'
      preLoaderRoute: typeof AuthenticatedImpressorasNovoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/impressoras/$id': {
      id: '/_authenticated/impressoras/$id'
      path: '/impressoras/$id'
      fullPath: '/impressoras/$id'
      preLoaderRoute: typeof AuthenticatedImpressorasIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ativos/novo': {
      id: '/_authenticated/ativos/novo'
      path: '/ativos/novo'
      fullPath: '/ativos/novo'
      preLoaderRoute: typeof AuthenticatedAtivosNovoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ativos/$id': {
      id: '/_authenticated/ativos/$id'
      path: '/ativos/$id'
      fullPath: '/ativos/$id'
      preLoaderRoute: typeof AuthenticatedAtivosIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/printers/ingest': {
      id: '/api/public/printers/ingest'
      path: '/api/public/printers/ingest'
      fullPath: '/api/public/printers/ingest'
      preLoaderRoute: typeof ApiPublicPrintersIngestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/agent/heartbeat': {
      id: '/api/public/agent/heartbeat'
      path: '/api/public/agent/heartbeat'
      fullPath: '/api/public/agent/heartbeat'
      preLoaderRoute: typeof ApiPublicAgentHeartbeatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/agent/discovery': {
      id: '/api/public/agent/discovery'
      path: '/api/public/agent/discovery'
      fullPath: '/api/public/agent/discovery'
      preLoaderRoute: typeof ApiPublicAgentDiscoveryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedA3AgentRoute: typeof AuthenticatedA3AgentRoute
  AuthenticatedAlertasRoute: typeof AuthenticatedAlertasRoute
  AuthenticatedAuditoriaRoute: typeof AuthenticatedAuditoriaRoute
  AuthenticatedCategoriasRoute: typeof AuthenticatedCategoriasRoute
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedConsumiveisRoute: typeof AuthenticatedConsumiveisRoute
  AuthenticatedContratosRoute: typeof AuthenticatedContratosRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDescobertaRoute: typeof AuthenticatedDescobertaRoute
  AuthenticatedEmpresasRoute: typeof AuthenticatedEmpresasRoute
  AuthenticatedEtiquetasRoute: typeof AuthenticatedEtiquetasRoute
  AuthenticatedFornecedoresRoute: typeof AuthenticatedFornecedoresRoute
  AuthenticatedLicencasRoute: typeof AuthenticatedLicencasRoute
  AuthenticatedManutencaoRoute: typeof AuthenticatedManutencaoRoute
  AuthenticatedMovimentacoesRoute: typeof AuthenticatedMovimentacoesRoute
  AuthenticatedRelatoriosRoute: typeof AuthenticatedRelatoriosRoute
  AuthenticatedSugestoesCompraRoute: typeof AuthenticatedSugestoesCompraRoute
  AuthenticatedUsuariosRoute: typeof AuthenticatedUsuariosRoute
  AuthenticatedAtivosIdRoute: typeof AuthenticatedAtivosIdRoute
  AuthenticatedAtivosNovoRoute: typeof AuthenticatedAtivosNovoRoute
  AuthenticatedImpressorasIdRoute: typeof AuthenticatedImpressorasIdRoute
  AuthenticatedImpressorasNovoRoute: typeof AuthenticatedImpressorasNovoRoute
  AuthenticatedAtivosIndexRoute: typeof AuthenticatedAtivosIndexRoute
  AuthenticatedImpressorasIndexRoute: typeof AuthenticatedImpressorasIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedA3AgentRoute: AuthenticatedA3AgentRoute,
  AuthenticatedAlertasRoute: AuthenticatedAlertasRoute,
  AuthenticatedAuditoriaRoute: AuthenticatedAuditoriaRoute,
  AuthenticatedCategoriasRoute: AuthenticatedCategoriasRoute,
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedConsumiveisRoute: AuthenticatedConsumiveisRoute,
  AuthenticatedContratosRoute: AuthenticatedContratosRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDescobertaRoute: AuthenticatedDescobertaRoute,
  AuthenticatedEmpresasRoute: AuthenticatedEmpresasRoute,
  AuthenticatedEtiquetasRoute: AuthenticatedEtiquetasRoute,
  AuthenticatedFornecedoresRoute: AuthenticatedFornecedoresRoute,
  AuthenticatedLicencasRoute: AuthenticatedLicencasRoute,
  AuthenticatedManutencaoRoute: AuthenticatedManutencaoRoute,
  AuthenticatedMovimentacoesRoute: AuthenticatedMovimentacoesRoute,
  AuthenticatedRelatoriosRoute: AuthenticatedRelatoriosRoute,
  AuthenticatedSugestoesCompraRoute: AuthenticatedSugestoesCompraRoute,
  AuthenticatedUsuariosRoute: AuthenticatedUsuariosRoute,
  AuthenticatedAtivosIdRoute: AuthenticatedAtivosIdRoute,
  AuthenticatedAtivosNovoRoute: AuthenticatedAtivosNovoRoute,
  AuthenticatedImpressorasIdRoute: AuthenticatedImpressorasIdRoute,
  AuthenticatedImpressorasNovoRoute: AuthenticatedImpressorasNovoRoute,
  AuthenticatedAtivosIndexRoute: AuthenticatedAtivosIndexRoute,
  AuthenticatedImpressorasIndexRoute: AuthenticatedImpressorasIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiPublicAgentDiscoveryRoute: ApiPublicAgentDiscoveryRoute,
  ApiPublicAgentHeartbeatRoute: ApiPublicAgentHeartbeatRoute,
  ApiPublicPrintersIngestRoute: ApiPublicPrintersIngestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
